name: Hello World1

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: echo "Hello World1"
      - name: Print date
        run: date
      - name: Print directory
        run: ls -l
